modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "disablesigngui"
version = "2.0.0"
displayName = "NoSignGUI"
authors = "CoolAid48"
description = '''
Allows you to toggle the sign text interface off and on!
'''
logoFile = "assets/disablesigngui/icon.png"

[[mixins]]
config = "disablesigngui.neoforge.mixins.json"
